# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0018_auto_20180305_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title/Topic')),
                ('count', models.CharField(max_length=3, verbose_name='Total Count')),
                ('type', models.CharField(choices=[('Internatioanl', 'Internatioanl'), ('National', 'National')], default='Internatioanl', max_length=15, verbose_name='International/National')),
                ('publisher', models.CharField(max_length=200, verbose_name='Publisher')),
                ('isbn', models.CharField(max_length=50, verbose_name='ISBN')),
                ('pages', models.CharField(max_length=4, verbose_name='Page No')),
                ('year', models.CharField(max_length=4)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Faculty')),
            ],
            options={
                'verbose_name': 'Book Record',
                'verbose_name_plural': 'Book Records',
            },
        ),
    ]
