# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20180306_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='pages',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Page No'),
        ),
    ]
