# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20180306_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrecord',
            name='h_index',
            field=models.CharField(default='1', max_length=10, verbose_name='H Index'),
            preserve_default=False,
        ),
    ]
