# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-06 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_researchrecord_h_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchrecord',
            name='h_index',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='H Index'),
        ),
    ]
