# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20180305_1655'),
        ('storage', '0008_auto_20180306_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDPRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title/Topic')),
                ('venue', models.CharField(max_length=500, verbose_name='Venue')),
                ('date', models.DateField()),
                ('duration', models.CharField(help_text='Number of days', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Faculty')),
            ],
            options={
                'verbose_name': 'FDP/Workshop Record',
                'verbose_name_plural': 'FDP/Workshop Records',
            },
        ),
    ]
