# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_fdprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdprecord',
            name='duration',
            field=models.CharField(blank=True, help_text='Number of days', max_length=5, null=True),
        ),
    ]
