# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_auto_20180309_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrecord',
            name='indexing',
            field=models.CharField(choices=[('SCI/SCIE', 'SCI/SCIE'), ('Scopus', 'Scopus'), ('Others', 'Others')], default='SCI/SCIE', max_length=10),
        ),
    ]
