# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_researchrecord_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchrecord',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Month Year'),
        ),
    ]
