# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2023-11-06 15:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_auto_20190722_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrecord',
            name='count',
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='amount',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9-]*$')], verbose_name='Amount in INR (If Paid)'),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='issn',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9-xX]*$')], verbose_name='ISSN'),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='other',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Other Authors'),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='price',
            field=models.CharField(max_length=10, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='specify',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If other, specify'),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='sponsor',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Self', 'Self'), ('Other', 'Other')], default='Free', max_length=15, null=True, verbose_name='Sponsoring Authority'),
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='top',
            field=models.CharField(choices=[('Book', 'Book'), ('Book Chapter', 'Book Chapter')], default='Book', max_length=15, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='fdprecord',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='fdprecord',
            name='amount',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9-]*$')], verbose_name='Amount in INR (If Paid)'),
        ),
        migrations.AddField(
            model_name='fdprecord',
            name='date2',
            field=models.DateField(null=True, verbose_name='Date (to)'),
        ),
        migrations.AddField(
            model_name='fdprecord',
            name='specify',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If other, specify'),
        ),
        migrations.AddField(
            model_name='fdprecord',
            name='sponsor',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Self', 'Self'), ('Other', 'Other')], default='Free', max_length=15, null=True, verbose_name='Sponsoring Authority'),
        ),
        migrations.AddField(
            model_name='fdprecord',
            name='top',
            field=models.CharField(choices=[('FDP', 'FDP'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar')], default='FDP', max_length=15, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='amount',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9-]*$')], verbose_name='Amount in INR (If Paid)'),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='other',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Other Authors'),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(storage.models.wrapper, *(), **{'field': 'title', 'folder': 'research'})),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='presented',
            field=models.CharField(choices=[('Presented', 'Presented'), ('Published', 'Published'), ('Presented & Published', 'Presented & Published')], default='Presented', max_length=25, verbose_name='Presented/Published'),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='specify',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If other, specify'),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='specify2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='If other, specify'),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='sponsor',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Self', 'Self'), ('Other', 'Other')], default='Free', max_length=15, null=True, verbose_name='Sponsoring Authority'),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='student',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[yYnN]*$')], verbose_name='Paper with students (Y/N -  For Conference Only)'),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Faculty'),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='isbn',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9-xX]*$')], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='pages',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')], verbose_name='Total Pages'),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='publisher',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ,-]*$')], verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='year',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='fdprecord',
            name='date',
            field=models.DateField(null=True, verbose_name='Date (from)'),
        ),
        migrations.AlterField(
            model_name='fdprecord',
            name='duration',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='fdprecord',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Faculty'),
        ),
        migrations.AlterField(
            model_name='fdprecord',
            name='venue',
            field=models.CharField(max_length=500, null=True, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='researchrecord',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Faculty'),
        ),
        migrations.AlterField(
            model_name='researchrecord',
            name='indexing',
            field=models.CharField(choices=[('SCI/SCIE', 'SCI/SCIE'), ('Scopus', 'Scopus'), ('UGC Listed', 'UGC Listed'), ('Google Scholars', 'Google Scholars'), ('Others', 'Others'), ('Not Applicable', 'Not Applicable')], default='SCI/SCIE', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchrecord',
            name='isbn',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9-Xx]*$')], verbose_name='ISBN/ISSN'),
        ),
        migrations.AlterField(
            model_name='researchrecord',
            name='issue',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='researchrecord',
            name='pages',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9-]*$')], verbose_name='Page No'),
        ),
        migrations.AlterField(
            model_name='researchrecord',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='researchrecord',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='researchrecord',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Month Year'),
        ),
    ]
