# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 14:08
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('profile_pic', ckeditor_uploader.fields.RichTextUploadingField()),
                ('designation', models.CharField(max_length=150, verbose_name='Designation')),
                ('phone_number', models.CharField(blank=True, help_text='Phone Number (without Regional Code)', max_length=10, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254)),
                ('shift', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], help_text='Morning or Evening', max_length=1, verbose_name='Shift')),
                ('department', models.CharField(help_text='Eg. CSE / IT / EEE', max_length=100, verbose_name='Department')),
                ('date_of_joining', models.DateField(blank=True, null=True, verbose_name='Date Of Joining')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
