# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.FileField(upload_to=b''),
        ),
    ]
