# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Page - Achievement', 'verbose_name_plural': 'Page - Achievements'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Content - Attendance', 'verbose_name_plural': 'Content - Attendance'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Page - Event', 'verbose_name_plural': 'Page - Events'},
        ),
        migrations.AlterModelOptions(
            name='latestnews',
            options={'verbose_name': 'Right - Latest News', 'verbose_name_plural': 'Right - Latest News'},
        ),
        migrations.AlterModelOptions(
            name='marquee',
            options={'verbose_name': 'Sliding Text', 'verbose_name_plural': 'Sliding Text'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Right - Notice', 'verbose_name_plural': 'Right - Notices'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page - All Other', 'verbose_name_plural': 'Page - All Others'},
        ),
        migrations.AlterModelOptions(
            name='primarymenu',
            options={'verbose_name': 'Menu - Left', 'verbose_name_plural': 'Menu - Left'},
        ),
        migrations.AlterModelOptions(
            name='primarynavigationmenu',
            options={'verbose_name': 'Menu - Top', 'verbose_name_plural': 'Menu - Top'},
        ),
        migrations.AlterModelOptions(
            name='secondarymenu',
            options={'verbose_name': 'Menu - Secondary', 'verbose_name_plural': 'Menu - Secondary'},
        ),
        migrations.AlterModelOptions(
            name='secondarynavigationmenu',
            options={'verbose_name': 'Menu - Secondary', 'verbose_name_plural': 'Menu - Secondary'},
        ),
        migrations.AlterModelOptions(
            name='studentsociety',
            options={'verbose_name': 'Page - Society', 'verbose_name_plural': 'Page - Societies'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name': 'Content - Syllabus', 'verbose_name_plural': 'Content - Syllabus'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Content - Time Table', 'verbose_name_plural': 'Content - Time Tables'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='experience',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Experience'),
        ),
    ]
