# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('APPLIED SCIENCES', 'Applied Sciences')], default='CSE', help_text='Department Name', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userdepartment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Department'),
        ),
    ]
