# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170305_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='qualifications',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
