# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 13:46
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_customuser_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('faculty', 'Faculty'), ('department', 'Department'), ('latest news', 'Latest News'), ('notice', 'Notice & Circular'), ('achievement', 'Achievement'), ('Attendaccnce', 'Attendance'), ('Event', 'Event'), ('Sliding Text', 'Sliding Text'), ('All Other', 'Pages'), ('Menu - Left', 'Menu - Left'), ('Menu - Top', 'Menu - Top'), ('Menu - Secondary', 'Menu - Secondary'), ('Society', 'Society'), ('Syllabus', 'Syllabus'), ('Time Table', 'Time Table')], max_length=159, null=True),
        ),
    ]
