# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170319_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Master', 'Master'), ('Dr', 'Dr')], default=1, max_length=10),
        ),
    ]
