# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170319_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepartment',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], default='Morning', max_length=10, verbose_name='Shift'),
        ),
    ]
