# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170310_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpage',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tab',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
