# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_userdepartment_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdepartment',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], default='M', max_length=10, verbose_name='Shift'),
        ),
    ]
