# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170121_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(upload_to='faculty'),
        ),
    ]
