# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170311_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpage',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tab',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
