# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170315_2058'),
        ('web', '0005_auto_20170319_1427'),
    ]

    operations = [
    ]
