# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-21 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170121_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text to display', max_length=250)),
                ('link', models.URLField(help_text='Link for the News')),
                ('new', models.BooleanField(default=True, help_text='This places a New Flag on th link')),
                ('visible', models.BooleanField(default=True, help_text='Whether the News is Visible on Main Page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Latest News',
                'verbose_name_plural': 'Latest News',
            },
        ),
        migrations.CreateModel(
            name='PrimaryMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Primary Menu',
                'verbose_name_plural': 'Primary Menus',
            },
        ),
        migrations.CreateModel(
            name='SecondaryMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.PrimaryMenu')),
            ],
            options={
                'verbose_name': 'Secondary Menu',
                'verbose_name_plural': 'Secondary Menus',
            },
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
