# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170320_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsociety',
            name='order',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
