# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20170327_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('1HOD', 'HOD'), ('2Professor', 'Professor'), ('3Assistant Professor', 'Assistant Professor'), ('4Associate Professor', 'Associate Professor'), ('5Reader', 'Reader')], max_length=30),
        ),
    ]
