# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170121_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='category',
            field=models.CharField(choices=[('office', 'Office Staff'), ('accounts', 'Accounts'), ('library', 'Library Staff'), ('placement', 'Placement Staff'), ('teaching', 'Teaching Faculty')], default='teaching', max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], default='M', help_text='Morning or Evening', max_length=1, verbose_name='Shift'),
        ),
    ]
