# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20170401_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
