# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-07 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20170401_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('1HOD', 'HOD'), ('2Professor', 'Professor'), ('3Associate Professor', 'Associate Professor'), ('4Reader', 'Reader'), ('5Assistant Professor', 'Assistant Professor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Master', 'Master'), ('Dr', 'Dr'), ('Prof', 'Prof')], default=1, max_length=10),
        ),
    ]
