# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20170121_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='category',
            field=models.CharField(choices=[('office', 'Office Staff'), ('accounts', 'Accounts'), ('library', 'Library Staff'), ('placement', 'Placement Staff'), ('teaching', 'Teaching Faculty')], default='teaching', max_length=30),
        ),
    ]
