# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20170607_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='department',
            name='sort_faculty',
            field=models.CharField(choices=[('1', 'Name wise'), ('2', 'Designation wise'), ('3', 'Date-of-joining wise'), ('4', 'Custom Order Specified')], default='1', max_length=1, verbose_name='Faculty Sorting Criteria'),
        ),
    ]
