# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20170121_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, help_text='Eg. CSE / IT / EEE', max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
