# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20170802_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Account Links',
                'verbose_name_plural': 'Social Account Links',
            },
        ),
    ]
