# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20170812_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
