# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_generaluploads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='GeneralUploads',
            new_name='GeneralUpload',
        ),
    ]
