# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 09:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20170121_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsociety',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
