# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_socialaccount_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='display_1st_assistant',
        ),
        migrations.RemoveField(
            model_name='department',
            name='display_2nd_assistant',
        ),
        migrations.AddField(
            model_name='department',
            name='display_assistant',
            field=models.BooleanField(default=False, help_text='Check if the list of Lab Assistants is to be displayed on the website', verbose_name='Display Lab Assistants'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('1HOD', 'HOD'), ('2Professor', 'Professor'), ('3Associate Professor', 'Associate Professor'), ('4Reader', 'Reader'), ('5Assistant Professor', 'Assistant Professor'), ('6Lab. Assistant', 'Lab. Assistant'), ('7Tech. Assistant', 'Tech. Assistant')], max_length=30),
        ),
    ]
