# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20170122_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryNavigationMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text to show in the Navigation', max_length=50)),
                ('link', models.CharField(help_text='Link to redirect to', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryNavigationMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text to show in the Navigation', max_length=50)),
                ('link', models.CharField(help_text='Link to redirect to', max_length=1000)),
            ],
        ),
    ]
