# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20180125_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('1HOD', 'HOD'), ('2Professor', 'Professor'), ('3Associate Professor', 'Associate Professor'), ('4Reader', 'Reader'), ('5Assistant Professor', 'Assistant Professor'), ('6Lab. Assistant', 'Lab. Assistant'), ('7Tech. Assistant', 'Tech. Assistant'), ('8Programmer', 'Programmer'), ('9Instructor', 'Instructor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Sh.', 'Sh.'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Master', 'Master'), ('Dr', 'Dr'), ('Prof', 'Prof')], default=1, max_length=10),
        ),
    ]
