# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-13 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20180305_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Sh.', 'Sh.'), ('Ms.', 'Ms.'), ('Miss', 'Miss'), ('Master', 'Master'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default=1, max_length=10),
        ),
    ]
