# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_primarynavigationmenu_secondarynavigationmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='additional_link',
            field=models.CharField(blank=True, help_text='Additional Link (if any)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='additional_title',
            field=models.CharField(blank=True, help_text='Additional Link Title (if any)', max_length=50, null=True),
        ),
    ]
