# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 14:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20170122_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_address', models.CharField(help_text='Page Address', max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
