# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-19 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20180313_1232'),
        ('web', '0019_auto_20180319_1557'),
    ]

    operations = [
    ]
