# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='pdf',
            new_name='lecture_plan',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='title',
        ),
        migrations.AddField(
            model_name='primarynavigationmenu',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='secondarynavigationmenu',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='Semester',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='branch',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'IT'), ('3', 'ECE'), ('4', 'EEE'), ('5', 'Applied Sciences')], default=1, help_text='Branch Name', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus',
            field=models.FileField(default=1, upload_to=web.models.image_name),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='title',
            field=models.CharField(help_text='Branch Name', max_length=50),
        ),
    ]
