# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2023-11-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import functools
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_merge_20180319_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='pdf',
            field=models.FileField(upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'title', 'folder': 'attendance'})),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'full_name', 'folder': 'faculty'})),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='additional_files',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'title', 'folder': 'news'})),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'title', 'folder': 'news'})),
        ),
        migrations.AlterField(
            model_name='marquee',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'title', 'folder': 'marquee'})),
        ),
        migrations.AlterField(
            model_name='notice',
            name='additional_files',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'title', 'folder': 'notices'})),
        ),
        migrations.AlterField(
            model_name='notice',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'title', 'folder': 'notices'})),
        ),
        migrations.AlterField(
            model_name='primarynavigationmenu',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'title', 'folder': 'navigations'})),
        ),
        migrations.AlterField(
            model_name='secondarynavigationmenu',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'title', 'folder': 'navigations'})),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='lecture_plan',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'title', 'folder': 'lecture_plan'})),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'title', 'folder': 'syllabus'})),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='pdf',
            field=models.FileField(upload_to=functools.partial(web.models.wrapper, *(), **{'field': 'title', 'folder': 'timetable'})),
        ),
    ]
