# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20170131_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='branch',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'IT'), ('3', 'ECE'), ('4', 'EEE'), ('5', 'Applied Sciences')], default=1, help_text='Branch Name', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='title',
            field=models.CharField(help_text='Batch Name', max_length=50),
        ),
    ]
