# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20170131_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Semester',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII'), ('8', 'VIII')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'IT'), ('3', 'ECE'), ('4', 'EEE'), ('5', 'Applied Sciences')], default=1, help_text='Branch Name', max_length=1),
            preserve_default=False,
        ),
    ]
