# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20170131_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Semester',
            new_name='semester',
        ),
    ]
