# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20170131_0726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralUpload',
        ),
    ]
