# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20170131_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, choices=[('1', 'CSE'), ('2', 'IT'), ('3', 'ECE'), ('4', 'EEE'), ('5', 'Applied Science')], max_length=1, null=True),
        ),
    ]
