# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20170131_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Eg: Campus Ground', max_length=100)),
                ('files', models.FileField(upload_to=web.models.image_name)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
