# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_generalupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='title',
            field=models.CharField(default='', help_text='text to display', max_length=100),
            preserve_default=False,
        ),
    ]
