# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 06:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_syllabus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 1, 6, 40, 49, 79675)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.image_name),
        ),
    ]
