# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_auto_20170201_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2017, 2, 1)),
        ),
    ]
